const buyerData = [
  { province: "Aceh", buyer: 219 },
  { province: "Bali", buyer: 322 },
  { province: "Kepulauan Bangka Belitung", buyer: 43 },
  { province: "Banten", buyer: 487 },
  { province: "Bengkulu", buyer: 321 },
  { province: "Gorontalo", buyer: 300 },
  { province: "Papua Barat", buyer: 19 },
  { province: "Jakarta", buyer: 335 },
  { province: "Jambi", buyer: 90 },
  { province: "Jawa Barat", buyer: 552 },
  { province: "Jawa Tengah", buyer: 578 },
  { province: "Jawa Timur", buyer: 200 },
  { province: "Kalimantan Barat", buyer: 500 },
  { province: "Kalimantan Selatan", buyer: 231 },
  { province: "Kalimantan Tengah", buyer: 111 },
  { province: "Kalimantan Timur", buyer: 216 },
  { province: "Kalimantan Utara", buyer: 300 },
  { province: "Kepulauan Riau", buyer: 100 },
  { province: "Lampung", buyer: 14 },
  { province: "Maluku Utara", buyer: 81 },
  { province: "Maluku", buyer: 340 },
  { province: "Nusa Tenggara Barat", buyer: 65 },
  { province: "Nusa Tenggara Timur", buyer: 11 },
  { province: "Papua", buyer: 31 },
  { province: "Riau", buyer: 65 },
  { province: "Sulawesi Barat", buyer: 72 },
  { province: "Sulawesi Selatan", buyer: 112 },
  { province: "Sulawesi Tengah", buyer: 341 },
  { province: "Sulawesi Tenggara", buyer: 223 },
  { province: "Sulawesi Utara", buyer: 321 },
  { province: "Sumatera Barat", buyer: 416 },
  { province: "Sumatera Selatan", buyer: 217 },
  { province: "Sumatera Utara", buyer: 321 },
  { province: "Yogyakarta", buyer: 574 }
];
